name: infra-cd
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["infra-ci"]
    # branches: [uat]
    types: 
      - completed

permissions:
  id-token: write
  contents: write

env:
  IMAGE_NAME: infra

jobs:
  infra-cd:
    if: |
       github.event.workflow_run.conclusion == 'success'
    runs-on: ${{ vars.RUNNER }}
    
    steps:
    - name: Access Repository Tag Variable
      run: |
        TAG=${{ vars.TAG }}
        echo "Using tag from repository variable: $TAG"
        echo "TAG=$TAG" >> "$GITHUB_ENV"

   # Checkout the branch
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ vars.BRANCH }}
        submodules: true
        token: ${{ secrets.TAG_TOKEN }}

    - name: Set manifest folder names
      run: |
         if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
            echo "FOLDER=uat" >> $GITHUB_ENV
         else
            echo "FOLDER=prod" >> $GITHUB_ENV
         fi

  ## Sharepoint tasks      
    - name: Get SharePoint Access Token
      id: get_token
      env:
        CLIENT_ID: ${{ secrets.ENV_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.ENV_CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.ENV_TENANT_ID }}
        SITENAME: Trumio-env
      run: |
          response=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=${{ env.CLIENT_ID }}&client_secret=${{ env.CLIENT_SECRET }}&grant_type=client_credentials&resource=https://graph.microsoft.com" "https://login.microsoftonline.com/${{ env.TENANT_ID }}/oauth2/token")
          echo "token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV
      
    - name: Retrieve Site ID
      id: get_site_id
      run: |
          site_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
          "https://graph.microsoft.com/v1.0/sites?search=${{ env.SITENAME }}")
          echo "site_id=trumio.sharepoint.com,0702a39f-d261-4be5-b3d4-76525995bc85,b3578a0e-9132-47da-bf61-cc572bf23ced" >> $GITHUB_ENV

    - name: Set SharePoint File Name Based on Tag
      run: |
        if [[ "${{ env.TAG }}" == uat_* ]]; then
          echo "FILENAME=env-uat.txt" >> $GITHUB_ENV
          echo "NAMESPACE=uat" >> $GITHUB_ENV
          echo "Namespace set to: ${{ env.NAMESPACE }}"

        elif [[ "${{ env.TAG }}" == tru-uat_* ]]; then
          echo "FILENAME=env-tru-uat.txt" >> $GITHUB_ENV
          echo "NAMESPACE=tru-uat" >> $GITHUB_ENV
          echo "Namespace set to: ${{ env.NAMESPACE }}"

        elif [[ "${{ env.TAG }}" == v* ]]; then
          echo "FILENAME=env-prod.txt" >> $GITHUB_ENV
          echo "NAMESPACE=prod" >> $GITHUB_ENV
          echo "Namespace set to: ${{ env.NAMESPACE }}"

        elif [[ "${{ env.TAG }}" == tru-prod_* ]]; then
          echo "FILENAME=env-tru-prod.txt" >> $GITHUB_ENV
          echo "NAMESPACE=tru-prod" >> $GITHUB_ENV
          echo "Namespace set to: ${{ env.NAMESPACE }}"
        else
          echo "Error: Unrecognized environment tag format."
          exit 1
        fi
                     
    - name: Fetch Download URL from SharePoint
      id: get_download_url
      run: |
          file_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
          "https://graph.microsoft.com/v1.0/sites/${{ env.site_id }}/drive/root:/${{ env.FOLDER }}/${{ env.FILENAME }}")
          echo "File response: $file_response"
          download_url=$(echo $file_response | jq -r '."@microsoft.graph.downloadUrl"')
          echo "Download URL: $download_url"
          echo "download_url=$download_url" >> $GITHUB_ENV
          
    - name: Display Download URL
      run: |
          echo "Download URL:"
          echo "${{ env.download_url }}"

    - name: Download File from SharePoint
      run: |
          if [ -z "${{ env.download_url }}" ]; then
            echo "Error: Download URL is empty"
            exit 1
          fi
          curl -L "${{ env.download_url }}" --output secrets.txt
          echo "File downloaded successfully."
    

    ########################## Keyvault-update ####################################

    - name: Install Azure cli        
      run: |
            sudo apt-get install ca-certificates curl apt-transport-https lsb-release
            curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            AZ_REPO=$(lsb_release -cs)
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            sudo apt-get update
            sudo apt-get install azure-cli

    - name: Set Azure environment
      id: azure
      run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
              echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID_UAT }}" >> $GITHUB_ENV
              echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
              echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
              echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET_UAT }}" >> $GITHUB_ENV
          else
              echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
              echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
              echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
              echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          fi
      shell: bash

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ env.azure_clientid }}","clientSecret":"${{ env.azure_clientsecret }}","subscriptionId":"${{ env.azure_subscriptionid }}","tenantId":"${{ env.azure_tenantid }}"}'
  
    - name: Azure Keyvault
      id: keyvault
      run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
              echo "rg_name=${{ vars.UAT_RG }}" >> $GITHUB_ENV
              echo "aks_name=${{ vars.UAT_AKS }}" >> $GITHUB_ENV
              echo "keyvault_name=${{ vars.UAT_AKV }}" >> $GITHUB_ENV
              echo "secret_name=${{ vars.UAT_AKV_SEC }}" >> $GITHUB_ENV
          else
              echo "rg_name=${{ vars.PROD_RG }}" >> $GITHUB_ENV
              echo "aks_name=${{ vars.PROD_AKS}}" >> $GITHUB_ENV
              echo "keyvault_name=${{ vars.PROD_AKV }}" >> $GITHUB_ENV
              echo "secret_name=${{ vars.PROD_AKV_SEC }}" >> $GITHUB_ENV
          fi

    - name: Update Key Vault Secret
      run: |
            az keyvault secret set --vault-name ${{ env.keyvault_name }} --name ${{ env.secret_name }} --value '${{ github.workspace }}/secrets.txt' 

  ########################## Cluster Deployment ####################################

    - name: ACR Environment
      id: acr
      run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
              echo "registry_url=${{ secrets.UAT_REGISTRY_URL }}" >> $GITHUB_ENV
              echo "registry_username=${{ secrets.UAT_REGISTRY_USERNAME }}" >> $GITHUB_ENV
              echo "registry_password=${{ secrets.UAT_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          else
              echo "registry_url=${{ secrets.REGISTRY_URL }}" >> $GITHUB_ENV
              echo "registry_username=${{ secrets.REGISTRY_USERNAME }}" >> $GITHUB_ENV
              echo "registry_password=${{ secrets.REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          fi

# Update Image, namespace and nodeSelector using yaml-update-action
    - name: Update deployment yml with multiple fields
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/${{ env.FOLDER }}/deployment_infra_be.yml'
        branch: ${{ vars.MANIFEST }}
        targetBranch: ${{ vars.MANIFEST }}
        commitUserName: infant-tr  
        commitUserEmail: infant.rex@trumio.ai  
        token: ${{ secrets.TAG_TOKEN }}
        description: 'Update deployment properties'
        message: 'Update deployment configurations'
        title: 'Deployment Config Updates'
        changes: |
          {
            "spec.template.spec.containers[0].image": "${{ env.registry_url }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}",
            "metadata.namespace": "${{ env.NAMESPACE }}",
            "spec.template.spec.nodeSelector.workload": "${{ vars.ENVIRONMENT }}"
          }

    - name: Update Deployment yaml for Site24x7
      if: ${{ vars.MANIFEST == 'production' && vars.SITE24X7 == 'false' }}
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/${{ env.FOLDER }}/deployment_infra_be_site247.yml'
        branch: ${{ vars.MANIFEST }}
        targetBranch: ${{ vars.MANIFEST }}
        commitUserName: infant-tr  
        commitUserEmail: infant.rex@trumio.ai  
        token: ${{ secrets.TAG_TOKEN }}
        description: 'Update deployment properties'
        message: 'Update deployment configurations'
        title: 'Deployment Config Updates'
        changes: |
          {
            "spec.template.spec.containers[0].image": "${{ env.registry_url }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}",
            "metadata.namespace": "${{ env.NAMESPACE }}",
            "spec.template.spec.nodeSelector.workload": "${{ vars.ENVIRONMENT }}"
          }

    - name: Update namespace using yaml-update-action
      uses: fjogeleit/yaml-update-action@main
      with:
          valueFile: 'manifests/${{ env.FOLDER }}/service_infra_be.yml'
          propertyPath: 'metadata.namespace'
          value: ${{ env.NAMESPACE }}
          branch: ${{ vars.MANIFEST }}
          targetBranch: ${{ vars.MANIFEST }}
          commitUserName: infant-tr  
          commitUserEmail: infant.rex@trumio.ai  
          token: ${{ secrets.TAG_TOKEN }}

    - run: |
          cat manifests/${{ env.FOLDER }}/deployment_infra_be.yml
   # Set the target AKS cluster.
    - uses: azure/aks-set-context@v4
      with:
        cluster-name: ${{ env.aks_name }}
        resource-group: ${{ env.rg_name }}

    #install kubectl on container (runner)
    - uses: azure/setup-kubectl@v4
      with:
        version: 'v1.28.2' # default is latest stable
      id: install
    
    # to access ACR from runner
    - uses: Azure/k8s-create-secret@v4
      with:
        container-registry-url: ${{ env.registry_url }}
        container-registry-username: ${{ env.registry_username }}
        container-registry-password: ${{ env.registry_password }}
        secret-name: k8s-secret

    - name: Set secret name
      run: |
         if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
            echo "secret=trumio-vault" >> $GITHUB_ENV
         else
            echo "secret=trumio-vault-prod" >> $GITHUB_ENV
         fi
    
    # K8s secret
    - name: K8s secret
      run: |
          kubectl create secret generic ${{ env.secret }} --from-env-file=secrets.txt --dry-run=client -o yaml | kubectl apply -f - -n ${{ env.NAMESPACE }}
      # echo "${{ secrets.ENV_UAT }}" > secrets.txt 

    - name: Secret time-lapse
      run: sleep 30s
      shell: bash
      
    ##to deploy on AKS
    - uses: Azure/k8s-deploy@v5
      with:
        action: deploy
        namespace: '${{ env.NAMESPACE }}'
        manifests: |
          manifests/${{ env.FOLDER }}/${{ vars.MANIFEST == 'production' && vars.SITE24X7 == 'false' && 'deployment_infra_be_site247.yml' || 'deployment_infra_be.yml' }}
          manifests/${{ env.FOLDER }}/service_infra_be.yml

    ##Docker Logout
    - name: docker logout
      run: |
            docker logout ${{ env.registry_url }}
